### ISSUE TITLE
Blender crashes when importing bedroom.dif

### ISSUE THREAD

**Issue by meowsandstuff** [RandomityGuy/io_dif#4]
[bedroom.zip](https://github.com/RandomityGuy/io_dif/files/12567635/bedroom.zip)
No error is provided when it happens. Here's the dif for sample.

**Comment by RandomityGuy** [comment]
What version of blender are you using? I tried loading the dif in the Blender version I have, i.e 3.3.1 and it loads fine.
Looking at the Blender python API breaking changes, the addon supports up to Blender 3.4 beyond which I have yet to update it (TODO) for the newer versions.

**Comment by meowsandstuff** [comment]
I'm using the latest version, 3.6.2

**Comment by RandomityGuy** [comment]
Yeah the plugin doesn't function properly on the latest version, yet to update. Try an older blender version such as 3.3
